
package com.oracle.xmlns.apps.cdm.foundation.parties.locationservice.applicationmodule;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LocationService", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/parties/locationService/applicationModule/", wsdlLocation = "https://adc-fap1294-crm.oracledemos.com/foundationParties/LocationService?WSDL")
public class LocationService_Service
    extends Service
{

    private final static URL LOCATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCATIONSERVICE_EXCEPTION;
    private final static QName LOCATIONSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/cdm/foundation/parties/locationService/applicationModule/", "LocationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://adc-fap1294-crm.oracledemos.com/foundationParties/LocationService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCATIONSERVICE_WSDL_LOCATION = url;
        LOCATIONSERVICE_EXCEPTION = e;
    }

    public LocationService_Service() {
        super(__getWsdlLocation(), LOCATIONSERVICE_QNAME);
    }

    public LocationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCATIONSERVICE_QNAME, features);
    }

    public LocationService_Service(URL wsdlLocation) {
        super(wsdlLocation, LOCATIONSERVICE_QNAME);
    }

    public LocationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCATIONSERVICE_QNAME, features);
    }

    public LocationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocationService
     */
    @WebEndpoint(name = "LocationServiceSoapHttpPort")
    public LocationService getLocationServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/cdm/foundation/parties/locationService/applicationModule/", "LocationServiceSoapHttpPort"), LocationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocationService
     */
    @WebEndpoint(name = "LocationServiceSoapHttpPort")
    public LocationService getLocationServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/cdm/foundation/parties/locationService/applicationModule/", "LocationServiceSoapHttpPort"), LocationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCATIONSERVICE_EXCEPTION!= null) {
            throw LOCATIONSERVICE_EXCEPTION;
        }
        return LOCATIONSERVICE_WSDL_LOCATION;
    }

}
